export {
  IconEye,
  IconEraser,
  IconAdjustmentsAlt,
  IconSortDescending,
  IconAirConditioning,
  IconArrowsMaximize,
  IconBrandWhatsapp,
  IconCalendarStats,
  IconMail,
  IconNumber,
  IconPhone,
  IconUser,
  IconMap2,
  IconMapPin,
  IconCash,
  IconCalendarWeek,
  IconTrash,
  IconPlus,
  IconEdit,
  IconTable,
  IconLayoutDashboard,
} from "@tabler/icons-react";
